pub mod registry;
pub mod system_info;
pub mod file_ops;
pub mod app_lifecycle;
pub mod shell;
pub mod internet;
pub mod knowledge;
pub mod system_config;
pub mod power;
pub mod process;
pub mod documents;
pub mod communication;
pub mod interaction;
pub mod disk;
pub mod scheduler;
pub mod precognitive;
pub mod vision;
pub mod desktop;
pub mod developer;
pub mod rag;
pub mod proactive;
pub mod i18n;

pub use registry::{ToolRegistry, ToolDef, ToolHandler};
